platform :ios, '5.0'
pod 'FlatUIKit'
pod 'TTTAttributedLabel'
pod 'Appirater'
pod 'TestFlightSDK'
pod 'Reachability'
pod 'MBProgressHUD'
pod 'PSCollectionView'
pod 'MKNetworkKit'
pod 'ViewDeck'
pod 'UIImage-Categories'
pod 'SDWebImage'
